const vars = {
    // Common variables
    instance: 'atzs',
    enviroment: 'dev',
    pass: 's74ffw1z4rd@1234',
    country: 'USA',
    address: '25020 Las Brisas Road',
    lat: '33.573844',
    long: '-117.1820404',
    city: 'Murrieta',
    state: 'California',
    shState: 'CA',
    zip: '92562',
    region: 'Pacific',
    branch: 'Socal',
    payType: 'Hourly Pay',
    status: 'Active',
    // Employee and Onboarding Variables 
    fName: 'Rajesh',
    mName: 'Middle',
    lName: 'Koothrappali',
    nName: 'Nickname',
    email: 'atzael+rajesh@staffwizard.com',
    dob: '01-01-1989',
    phone: '618-999-98-82',
    ssn: '999-99-9882',
    cardNum: '111111111111123',
    hire: '01-01-2022',
    join: '01-03-2022',
    payID: '02594',
    jobTitle: 'SMS Credentials',
    marital: 'Married',
    prevComp: 'CNC Designer',
    business: 'Metal-Steel Manufacter',
    pay: '2.25',
    postType: 'CNC programmer and 3D designer',
    postBusiness: 'CNC programmer and 3D designer',
    postArea: 'Durango, Dgo.',
    refer: 'Linkedin',
    dtStart: '2014',
    dtEnd: '2022',
    // Client Variables
    compName: 'Client For Test Default Report Types',
    primName: 'Atzael Irigoyen',
    primEmail: 'atzael+default@staffwizard.com',
    postName: 'Post Locations For Test Default Reports',
    pay: '10.00',
    bill: '11.00',
    // Schedule Variables
    schdlWeek: ''
}

export default vars;